### ISSUE TITLE
Meeting: Decentralizing LCSH

### ISSUE THREAD

**Issue by flyingzumwalt** [ipld/persistent-metadata#1]
Meeting: Decentralizing LCSH
====

Date: 2017-01-20

## Participants:
* flyingzumwalt
* edsu
* cmh2166

# Notes:

## References:
* [Decentralized Web Primer](https://www.gitbook.com/book/flyingzumwalt/decentralized-web-primer/details)
* [IPLD website](http://ipld.io/)
* Related: [data.gov on IPFS](https://github.com/ipfs/archives/issues/87)

## Next Steps:
- [x] EdS, ChristinaH: Review resources listed at top. Some not complete, but worth looking at
    - IPLD specs give good examples of concepts discussed briefly here
- [x] MattZ will start [GH repo](https://github.com/ipld/authenticated-metadata), add @nicola, can ask him questions directly.
    - Making this a strong reference example of putting metadata into IPLD
    - Use this space for communication, questions.
- [x] MattZ will schedule follow-up call on Monday 30th, 3 PM Eastern, MattZ will send out call info.
    - Handling urgency: being able to say there is a project that is going to happen, with these people, kind of enough right now to handle urgency of these questions. Gives space also to motivated folks to bring ideas, questions, topics.
    - Secondarily is having the reference example out there.
- [x]  MattZ: See if @barmintor can join us.

## Why this project:
- wanting to follow up in part on Christina's talk at code4lib 2016 (being able to do data work, overuse of id.loc.gov + related lc data endpoints, no way to share data updates back to LC)
- decentralizing this LC data work makes sense
- then, work around IPLD evolved, extremely relevant to the above needs, as it gives right format for expressing this data in decentralized way

**Key Goal**: Pull out LCSH data, convert to IPLD, then load into IPFS. Write up, informally, method, snags, pluses, etc. 

Following this, data.gov situation came up
- downloaded data.gov datasets + decentralizing that is one task
- but question of how to deal with datasets metadata, link to datasets, manage in decentralized way is difficult question
- MattZ wants response to this issue area being raised is this LCSH to IPLD/IPFS project being a response to showing how this could work

## Responses to this proposal:
- EdS: this project seems focused, which is good.
    - chatting with MattZ a few months ago, get all LC data, put it into IPFS/IPLD, then you modify the data, how do you support that?
    - LC as Authority is almost an artifact, all people creating subject headings were in certain institutions, managed by centralized institution
    - This management of decentralized authorities data for changes from different communities, groups, institutions seems a key part of the story
- MattZ: Good point to discuss IPLD
    - accorinding to spec, in order to convert linked data to IPLD you can just express it as JSON-LD and then persist directly as IPLD (in theory)
    - will hit some problems, bumps
    - [sorry, overview] IPFS structure, thinking of it like one thinks of Git, allows specificity to point to specific hashes / data forks. IPLD is trying to be then generic way to express any merkle dag.
    - EdS: so if with forked data, push back to IPFS, what is the relationship? Is it hereditary? Do I need to indicate relationship?
    - MattZ: It acts like commit history in Git, then have ability to switch between, compare, etc. different commits.
    - EdS: Is commit version history part of IPLD?
    - MattZ: Separate. Expressing version history in IPLD is easy. Nobody has built tooling for this yet. ... Not part of work necessarily of the proposed project here.
    - MattZ: one of the challenges is that you will need to have stable identifiers for use in descriptions (e.g. a book by Tom Brown) but also there will need to be identifiers for the particular snapshot version of the metadata.   

Why EdS, ChristinaH on this? Next Steps?
- Christina working on consuming side of data
- EdS originally published id.loc.gov LOD, deep knowledge of that data
- So what does this look like:
    - EdS: Need to do some learning on IPFS, has just been following from afar
    - First steps: just using IPFS, getting familiar with it, tools
    - ChristinaH: relationship to LD4L stuff at Cornell
    - EdS: Where he works, there is small group, under a DH umbrella, work load right now also is quite busy in next few months
- Timeframe?: 
    - MattZ: Talk about at Code4Lib would be great, even if not done
    - Also, the data.gov issue impacts the timeline. Climate data is getting written to a number of destinations. Triggers cascade of now its on IPFS, what is it like to share burden of holding all this stuff, versions, etc. 
    - Question of decentralized metadata is one of those follow-up questions. So sooner LCSH project is rolling, sooner MattZ can respond to data.gov needs, redirect ideas and curiousity.
    - Other possible related project: contract BArmintor to write a LDP endpoint that writes to IPLD.

**Comment by rvagg** [comment]
closing for archival
